### ISSUE TITLE
No module named askbot_slack_config

### ISSUE THREAD

**Issue by ghostsquad** [jonmbake/askbot-slack#2]
this didn't work for me. here is the error I'm getting when askbot tries to load askbot_slack

```
Apr 08 20:49:25 test python[24163]: File "/usr/lib/python2.7/site-packages/askbot_slack.py", line 3, in <module>
Apr 08 20:49:25 test python[24163]: from askbot_slack_config import config
Apr 08 20:49:25 test python[24163]: ImportError: No module named askbot_slack_config
```

**Comment by ghostsquad** [comment]
is the package old in Pip?

**Comment by jonmbake** [comment]
@ghostsquad Sorry about that. Forgot to update the Pip package. It should be good now:  https://pypi.python.org/pypi/askbot-slack.

**Comment by ghostsquad** [comment]
this still doesn't work. I uninstalled askbot_slack, tried reinstalling via pip. I also tried to install the `whl` file directly from pypi. I'm getting the same error.

**Comment by jonmbake** [comment]
It looks like I didn't do a `clean` before building the wheel so the old file was still hanging around. I did a clean and then rebuilt the `whl`. Can you try again uninstalling/reinstalling w/ pip? Make sure it is the _0.2.0_ version.

I currently do not have Askbot installed on my local development machine, but I did verify contents of the wheel:

```
> unzip -l dist/askbot_slack-0.2.0-py2.py3-none-any.whl
Archive:  dist/askbot_slack-0.2.0-py2.py3-none-any.whl
  Length     Date   Time    Name
 --------    ----   ----    ----
     2132  04-08-16 20:50   askbot_slack/__init__.py
     1046  04-08-16 20:50   askbot_slack/conf.py
      114  04-13-16 19:46   askbot_slack-0.2.0.dist-info/DESCRIPTION.rst
      760  04-13-16 19:46   askbot_slack-0.2.0.dist-info/metadata.json
       47  04-13-16 19:46   askbot_slack-0.2.0.dist-info/pbr.json
       13  04-13-16 19:46   askbot_slack-0.2.0.dist-info/top_level.txt
      110  04-13-16 19:46   askbot_slack-0.2.0.dist-info/WHEEL
      679  04-13-16 19:46   askbot_slack-0.2.0.dist-info/METADATA
      775  04-13-16 19:46   askbot_slack-0.2.0.dist-info/RECORD
 --------                   -------
     5676                   9 files
```

and `askbot_slack.py` is no longer present. It should work now.

**Comment by ghostsquad** [comment]
This looks like it works, but how do I go about setting this up to use a proxy. My askbot server is behind a proxy, and as such, it can't access the internet without a proxy configured.

Also, it seems that if the slack integration fails to post to slack, the question that was asked becomes corrupt. Clicking on the question results in a error page.
